const practiceCategories = [
  {
    id: 'job-interviews',
    title: 'Job Interviews',
    icon: 'user',
    description: 'Role-specific interviews for placements, internships, and career moves.',
  },
  {
    id: 'negotiation',
    title: 'Negotiation',
    icon: 'trend',
    description: 'Practice compensation, offers, promotions, and client conversations.',
  },
  {
    id: 'business',
    title: 'Business',
    icon: 'sparkles',
    description: 'Sharpen startup, investor, product, and fundraising conversations.',
  },
  {
    id: 'communication',
    title: 'Communication',
    icon: 'message',
    description: 'Build confidence for support, presentations, speaking, and discussions.',
  },
];

const practiceScenarios = [
  {
    id: 'hr-interview',
    title: 'HR Interview',
    category: 'job-interviews',
    icon: 'user',
    description: 'Practice introductions, motivation, strengths, and culture-fit answers.',
    estimatedDuration: '10-20 min',
    difficulty: 'Easy',
    defaultRole: 'Candidate',
    aiPersonality: 'Friendly HR Recruiter',
    openingPrompt: 'Welcome. To begin, please introduce yourself and tell me what kind of role you are targeting.',
    systemPrompt: 'You are a friendly HR recruiter. Ask realistic HR interview questions about background, motivation, strengths, weaknesses, teamwork, and culture fit.',
    recommendedSkills: ['Self introduction', 'Clarity', 'Confidence', 'Culture fit'],
  },
  {
    id: 'technical-interview',
    title: 'Technical Interview',
    category: 'job-interviews',
    icon: 'target',
    description: 'Answer realistic role-based technical questions with follow-ups.',
    estimatedDuration: '20-30 min',
    difficulty: 'Hard',
    defaultRole: 'Full Stack Developer',
    aiPersonality: 'Senior Software Engineer',
    openingPrompt: 'Let us start with your technical background. What projects best represent your current engineering ability?',
    systemPrompt: 'You are a senior software engineer conducting a practical technical interview. Ask role-appropriate technical questions, probe tradeoffs, and request concise reasoning.',
    recommendedSkills: ['Problem solving', 'System thinking', 'Code reasoning', 'Tradeoffs'],
  },
  {
    id: 'behavioral-interview',
    title: 'Behavioral Interview',
    category: 'job-interviews',
    icon: 'insight',
    description: 'Practice structured STAR answers for leadership and teamwork.',
    estimatedDuration: '15-20 min',
    difficulty: 'Medium',
    defaultRole: 'Candidate',
    aiPersonality: 'Experienced Hiring Manager',
    openingPrompt: 'Tell me about a time you handled a difficult project or team situation.',
    systemPrompt: 'You are an experienced hiring manager. Ask behavioral questions and encourage specific STAR-format answers with clear outcomes.',
    recommendedSkills: ['STAR method', 'Ownership', 'Reflection', 'Examples'],
  },
  {
    id: 'manager-round',
    title: 'Manager Round',
    category: 'job-interviews',
    icon: 'dashboard',
    description: 'Prepare for team-fit, ownership, execution, and collaboration questions.',
    estimatedDuration: '15-25 min',
    difficulty: 'Medium',
    defaultRole: 'Software Engineer',
    aiPersonality: 'Engineering Manager',
    openingPrompt: 'I would like to understand how you work with teams. What kind of environment helps you do your best work?',
    systemPrompt: 'You are an engineering manager evaluating execution, collaboration, ownership, communication, and team fit.',
    recommendedSkills: ['Ownership', 'Collaboration', 'Prioritization', 'Communication'],
  },
  {
    id: 'campus-placement',
    title: 'Campus Placement',
    category: 'job-interviews',
    icon: 'sparkles',
    description: 'Practice fresher-friendly placement interviews with fundamentals.',
    estimatedDuration: '15-25 min',
    difficulty: 'Medium',
    defaultRole: 'Fresher',
    aiPersonality: 'Campus Interview Panelist',
    openingPrompt: 'Please introduce yourself and walk me through one academic or personal project you are proud of.',
    systemPrompt: 'You are a campus placement interviewer. Ask fresher-friendly questions about fundamentals, projects, internships, communication, and career motivation.',
    recommendedSkills: ['Fundamentals', 'Projects', 'Confidence', 'Learning ability'],
  },
  {
    id: 'internship-interview',
    title: 'Internship Interview',
    category: 'job-interviews',
    icon: 'clock',
    description: 'Prepare for internship screens focused on potential and projects.',
    estimatedDuration: '10-20 min',
    difficulty: 'Easy',
    defaultRole: 'Intern',
    aiPersonality: 'Internship Interviewer',
    openingPrompt: 'What are you hoping to learn from this internship, and what have you built so far?',
    systemPrompt: 'You are an internship interviewer. Ask approachable questions about coursework, projects, curiosity, learning speed, and availability.',
    recommendedSkills: ['Projects', 'Curiosity', 'Basics', 'Coachability'],
  },
  {
    id: 'salary-negotiation',
    title: 'Salary Negotiation',
    category: 'negotiation',
    icon: 'trend',
    description: 'Practice compensation conversations with evidence and tact.',
    estimatedDuration: '10-15 min',
    difficulty: 'Medium',
    defaultRole: 'Candidate',
    aiPersonality: 'HR Compensation Manager',
    openingPrompt: 'Let us discuss compensation expectations. What range are you considering for this role?',
    systemPrompt: 'You are an HR compensation manager. Negotiate professionally, ask for reasoning, and test whether the user can advocate with market evidence.',
    recommendedSkills: ['Anchoring', 'Evidence', 'Professional tone', 'Tradeoffs'],
  },
  {
    id: 'offer-negotiation',
    title: 'Offer Negotiation',
    category: 'negotiation',
    icon: 'check',
    description: 'Discuss offer terms, joining dates, benefits, and alternatives.',
    estimatedDuration: '10-15 min',
    difficulty: 'Medium',
    defaultRole: 'Candidate',
    aiPersonality: 'Recruiter',
    openingPrompt: 'Congratulations on the offer. Which part of the package would you like to discuss?',
    systemPrompt: 'You are a recruiter discussing an offer. Explore compensation, joining date, benefits, competing options, and constraints.',
    recommendedSkills: ['Negotiation', 'Priorities', 'Clarity', 'Professionalism'],
  },
  {
    id: 'promotion-discussion',
    title: 'Promotion Discussion',
    category: 'negotiation',
    icon: 'arrowUpRight',
    description: 'Make a case for growth, scope, and impact.',
    estimatedDuration: '15-20 min',
    difficulty: 'Hard',
    defaultRole: 'Employee',
    aiPersonality: 'Engineering Manager',
    openingPrompt: 'Tell me why you believe you are ready for the next level.',
    systemPrompt: 'You are an engineering manager discussing promotion readiness. Ask for evidence of impact, scope, leadership, and consistency.',
    recommendedSkills: ['Impact', 'Scope', 'Evidence', 'Career framing'],
  },
  {
    id: 'freelance-client',
    title: 'Freelance Client',
    category: 'negotiation',
    icon: 'message',
    description: 'Handle pricing, scope, timelines, and difficult client expectations.',
    estimatedDuration: '10-20 min',
    difficulty: 'Hard',
    defaultRole: 'Freelancer',
    aiPersonality: 'Demanding Client',
    openingPrompt: 'I need this delivered quickly and cheaply. Why should I pay your proposed rate?',
    systemPrompt: 'You are a demanding freelance client. Challenge price, timeline, scope, revisions, and value while staying realistic.',
    recommendedSkills: ['Scope control', 'Pricing', 'Boundaries', 'Value'],
  },
  {
    id: 'business-negotiation',
    title: 'Business Negotiation',
    category: 'negotiation',
    icon: 'shield',
    description: 'Practice partnership and deal conversations with clear terms.',
    estimatedDuration: '15-25 min',
    difficulty: 'Hard',
    defaultRole: 'Business Lead',
    aiPersonality: 'Business Counterparty',
    openingPrompt: 'Before we agree on terms, I want to understand what you need and what you are willing to trade.',
    systemPrompt: 'You are a business counterparty negotiating a practical deal. Ask about goals, concessions, risks, value, and next steps.',
    recommendedSkills: ['BATNA', 'Concessions', 'Risk', 'Next steps'],
  },
  {
    id: 'startup',
    title: 'Startup Pitch',
    category: 'business',
    icon: 'sparkles',
    description: 'Present your idea and defend the opportunity to a seed investor.',
    estimatedDuration: '10-15 min',
    difficulty: 'Medium',
    defaultRole: 'Founder',
    aiPersonality: 'Seed Investor',
    openingPrompt: 'You have a few minutes. What problem are you solving, and why now?',
    systemPrompt: 'You are a tough but fair seed investor. Ask challenging questions about problem, market, business model, competition, and traction.',
    recommendedSkills: ['Problem framing', 'Market size', 'Business model', 'Traction'],
  },
  {
    id: 'investor-pitch',
    title: 'Investor Pitch',
    category: 'business',
    icon: 'target',
    description: 'Practice a sharper investor conversation with deeper follow-ups.',
    estimatedDuration: '15-25 min',
    difficulty: 'Hard',
    defaultRole: 'Founder',
    aiPersonality: 'VC Partner',
    openingPrompt: 'Give me the short version first: what are you building, who needs it, and why will this become large?',
    systemPrompt: 'You are a VC partner. Ask pointed questions about market, traction, defensibility, team, unit economics, and fundability.',
    recommendedSkills: ['Investor narrative', 'Traction', 'Defensibility', 'Unit economics'],
  },
  {
    id: 'product-demo',
    title: 'Product Demo',
    category: 'business',
    icon: 'play',
    description: 'Explain product value to a skeptical buyer or customer.',
    estimatedDuration: '8-12 min',
    difficulty: 'Medium',
    defaultRole: 'Product Lead',
    aiPersonality: 'Potential Customer',
    openingPrompt: 'I am interested, but I need to understand why this is better than what we already use.',
    systemPrompt: 'You are a potential customer evaluating a product demo. Ask about value, features, pricing, implementation, and alternatives.',
    recommendedSkills: ['Value proposition', 'Demo flow', 'Objection handling', 'Pricing'],
  },
  {
    id: 'fundraising',
    title: 'Fundraising',
    category: 'business',
    icon: 'trend',
    description: 'Handle questions about traction, growth, and your raise.',
    estimatedDuration: '12-18 min',
    difficulty: 'Hard',
    defaultRole: 'Founder',
    aiPersonality: 'VC Partner',
    openingPrompt: 'Walk me through your raise: how much capital, what milestone, and why this is the right time.',
    systemPrompt: 'You are a venture capitalist reviewing a fundraise. Ask about unit economics, milestones, runway, team, and competitive advantage.',
    recommendedSkills: ['Raise strategy', 'Metrics', 'Milestones', 'Runway'],
  },
  {
    id: 'vc-meeting',
    title: 'VC Meeting',
    category: 'business',
    icon: 'dashboard',
    description: 'Simulate a partner meeting with strategic investor questions.',
    estimatedDuration: '20-30 min',
    difficulty: 'Hard',
    defaultRole: 'Founder',
    aiPersonality: 'Investment Committee Partner',
    openingPrompt: 'Assume I have read the deck. What is the strongest reason this company should exist?',
    systemPrompt: 'You are an investment committee partner. Ask strategic, financial, and market questions with high standards.',
    recommendedSkills: ['Strategy', 'Market insight', 'Financial logic', 'Composure'],
  },
  {
    id: 'customer-support',
    title: 'Customer Support',
    category: 'communication',
    icon: 'shield',
    description: 'Handle tense customer conversations with empathy and control.',
    estimatedDuration: '10-15 min',
    difficulty: 'Medium',
    defaultRole: 'Customer Support',
    aiPersonality: 'Angry Customer',
    openingPrompt: 'I am frustrated. This issue has taken too long, and nobody has given me a clear answer.',
    systemPrompt: 'You are an angry customer. Express frustration realistically and evaluate whether the user listens, clarifies, and resolves the issue.',
    recommendedSkills: ['Empathy', 'De-escalation', 'Clarity', 'Resolution'],
  },
  {
    id: 'presentation-practice',
    title: 'Presentation Practice',
    category: 'communication',
    icon: 'play',
    description: 'Practice presenting ideas to a professional audience.',
    estimatedDuration: '10-20 min',
    difficulty: 'Medium',
    defaultRole: 'Presenter',
    aiPersonality: 'Professional Audience',
    openingPrompt: 'Please begin your presentation. I will interrupt with questions where clarity is needed.',
    systemPrompt: 'You are a professional audience member. Ask clarifying questions about structure, evidence, audience relevance, and takeaway.',
    recommendedSkills: ['Structure', 'Audience fit', 'Evidence', 'Takeaway'],
  },
  {
    id: 'public-speaking',
    title: 'Public Speaking',
    category: 'communication',
    icon: 'message',
    description: 'Build confidence for speeches, talks, and formal communication.',
    estimatedDuration: '10-20 min',
    difficulty: 'Easy',
    defaultRole: 'Speaker',
    aiPersonality: 'Speech Coach',
    openingPrompt: 'What topic are you speaking about, and what should your audience remember?',
    systemPrompt: 'You are a speech coach. Ask about audience, structure, opening, examples, pacing, and memorable closing.',
    recommendedSkills: ['Presence', 'Structure', 'Storytelling', 'Pacing'],
  },
  {
    id: 'group-discussion',
    title: 'Group Discussion',
    category: 'communication',
    icon: 'dashboard',
    description: 'Practice entering, balancing, and leading group discussions.',
    estimatedDuration: '15-20 min',
    difficulty: 'Medium',
    defaultRole: 'Participant',
    aiPersonality: 'Panel Moderator',
    openingPrompt: 'The topic is open for discussion. Start with your position and one supporting reason.',
    systemPrompt: 'You are a panel moderator for a group discussion. Challenge the user to be concise, balanced, evidence-led, and collaborative.',
    recommendedSkills: ['Conciseness', 'Listening', 'Evidence', 'Leadership'],
  },
  {
    id: 'college-viva',
    title: 'College Viva',
    category: 'communication',
    icon: 'clock',
    description: 'Prepare for oral exams, project explanations, and faculty questions.',
    estimatedDuration: '10-15 min',
    difficulty: 'Easy',
    defaultRole: 'Student',
    aiPersonality: 'Faculty Examiner',
    openingPrompt: 'Start by explaining your project or topic in simple terms.',
    systemPrompt: 'You are a faculty examiner. Ask concept, project, reasoning, and application questions suitable for a college viva.',
    recommendedSkills: ['Concepts', 'Project explanation', 'Reasoning', 'Confidence'],
  },
];

function getScenarioById(id) {
  return practiceScenarios.find((scenario) => scenario.id === id);
}

function getCategoryById(id) {
  return practiceCategories.find((category) => category.id === id);
}


const scenarioConfig = {
  practiceCategories,
  practiceScenarios,
  getScenarioById,
  getCategoryById,
};

module.exports = scenarioConfig;
module.exports.default = scenarioConfig;